[snowflake]
user = "dbtuser"
password = "dataAItest2026#"
account = "rlxazxg-ow84266"
warehouse = "COMPUTE_WH"
database = "INDUSTRIAL_PROCUREMENT_DB"
schema = "ANALYTICS"
role = "ACCOUNTADMIN"
